name = "frostbloom-fx"
account_id = "f7ea9826645e65279695a42b9b1042a8"
main = "./dist/worker.js"
compatibility_date = "2024-11-14"
send_metrics = false
{
  "observability": {
    "enabled": false,
    "head_sampling_rate": 1,
    "logs": {
      "enabled": true,
      "head_sampling_rate": 1,
      "persist": true,
      "invocation_logs": true
    },
    "traces": {
      "enabled": false,
      "persist": true,
      "head_sampling_rate": 1
    }
  }
}