name = "frostbloom-fx"
account_id = "f7ea9826645e65279695a42b9b1042a8"
main = "./dist/worker.js"
compatibility_date = "2024-11-14"
send_metrics = false

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[vars]
STANDARD_DOMAIN_LIST = "frostbloom-fx.frostbloom.workers.dev"
DIRECT_MEDIA_DOMAINS = "frostbloom-fx.frostbloom.workers.dev"
VIDEO_TRANSCODE_DOMAIN_LIST = "frostbloom-fx.frostbloom.workers.dev"
TEXT_ONLY_DOMAINS = "frostbloom-fx.frostbloom.workers.dev"
INSTANT_VIEW_DOMAINS = "frostbloom-fx.frostbloom.workers.dev"
GALLERY_DOMAINS = "frostbloom-fx.frostbloom.workers.dev"
OLD_EMBED_DOMAINS = "frostbloom-fx.frostbloom.workers.dev"
API_HOST_LIST = "api.fxtwitter.com,api-canary.fxtwitter.com"